### ISSUE TITLE
Elaboration on Section 3, Goal 3.11?

### ISSUE THREAD

**Issue by torgo** [ossf/education#53]
Just noting the [goal 3.11](https://github.com/ossf/education/blob/main/plan/3.0%20Reward%20and%20Incentivize%20Developers%20and%20Maintainers.md#311-goal-create-a-unified-approach-to-delivering-certification-and-badging-no-matter-where-such-training-has-been-delivered-building-upon-the-existing-linux-foundation-certification-infrastructure) doesn't have a lot of description and I'd like to better understand the subgoals and non-subgoals here. Specifically, as an organisation that delivers training / developer education I want to understand how any certification that we provide can confer appropriate OpenSSF badges / certification. Thanks!

**Comment by Salkimmich** [comment]
Updated with this language, but from an organizational perspective, would there be a better way to word (or to actually do) this from your point of view? 

## 3.11 Goal: Create a unified approach to delivering certification and badging no matter where such training has been delivered, building upon the existing Linux Foundation certification infrastructure. 

### Explanation
A unified digital certification and badging process should be available for all major training and hiring platforms. Our aim in this section is to ensure that the digital signature of each certification is widely distributable in Y2. This will require ensuring that each partnered platform adheres to a standardized format of content delivery, testing and validation when utalizing the educational pathways developed in Section 2 of this plan, so that there can be verified trust of the certification, while allowing for the widest distribution possible.

**Comment by SecurityCRob** [comment]
Any further conversation on this, or can we close?
